id: AD8D6DE7E
title: A Prayer for the Spread of Kyabje Dilgo Khyentse Rinpoche’s Termas
type: translation
pechas:
- I84FAA5AF
- IC4CF2AC4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:35:19.380654
  last_modified_at: 2023-01-04 11:35:19.380659
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I84FAA5AF/CF8C: 08FA
  IC4CF2AC4/6030: 08FA
